# Generated by Django 3.0.3 on 2020-07-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='BOOKED', max_length=20)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('creationTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('maxCapacity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=36)),
                ('duration', models.IntegerField(choices=[('30', '30 Minutes'), ('60', '1 Hour'), ('120', '2 Hour'), ('180', '3 Hour')], default=60)),
            ],
        ),
    ]
