# Generated by Django 3.0.3 on 2020-07-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200714_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(choices=[('30', '30 Minutes'), ('60', '1 Hour'), ('90', '1.5 Hour'), ('120', '2 Hour'), ('180', '3 Hour')], default=60),
        ),
    ]
