# Generated by Django 3.0.3 on 2020-07-29 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200723_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yelpBusinessId', models.CharField(max_length=50)),
                ('yelpRating', models.DecimalField(decimal_places=1, max_digits=10)),
                ('yelpCommentNum', models.IntegerField()),
                ('businessPartner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Partner')),
            ],
        ),
    ]
