# Generated by Django 3.0.3 on 2020-07-30 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_apimap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apimap',
            name='id',
        ),
        migrations.AlterField(
            model_name='apimap',
            name='businessPartner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='register.Partner'),
        ),
    ]
