# Generated by Django 3.0.3 on 2020-07-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yelpreview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yelpreview',
            name='timeCreated',
        ),
    ]
